name: CI-CD Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  IMAGE_NAME: sevenajay/netflix
  SONAR_PROJECT_KEY: netflix
  SONAR_PROJECT_NAME: netflix

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_PROJECT_KEY: ${{ env.SONAR_PROJECT_KEY }}
        SONAR_PROJECT_NAME: ${{ env.SONAR_PROJECT_NAME }}

    - name: Run Trivy FS Scan
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        trivy fs . > trivyfs.txt

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Image
      run: docker push $IMAGE_NAME:latest

    - name: Trivy Image Scan
      run: trivy image $IMAGE_NAME:latest > trivyimage.txt

    - name: Deploy to Kubernetes
      uses: azure/k8s-deploy@v4
      with:
        manifests: |
          ./Kubernetes/deployment.yml
          ./Kubernetes/service.yml
        images: ${{ env.IMAGE_NAME }}:latest
        kubectl-version: 'latest'
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Upload Scan Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: trivy-reports
        path: |
          trivyfs.txt
          trivyimage.txt
