name: CI-CD for Netflix Clone

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
      SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      K8S_MASTER_IP: ${{ secrets.K8S_MASTER_IP }}
      K8S_USER: ${{ secrets.K8S_USER }}
      K8S_PRIVATE_KEY: ${{ secrets.K8S_PRIVATE_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: SonarQube Scan
      run: |
        wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
        unzip sonar-scanner-cli-5.0.1.3006-linux.zip
        ./sonar-scanner-*/bin/sonar-scanner \
          -Dsonar.projectKey=Netflix \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ env.SONAR_TOKEN }}

    - name: Run OWASP Dependency Check
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/src \
          owasp/dependency-check \
          --project "Netflix" \
          --scan /src \
          --format "ALL" \
          --out /src/dependency-check-report \
          --disableAssemblyAnalysis \
          --timeout 120

    - name: Run Trivy FS Scan
      run: |
        docker run --rm -v ${{ github.workspace }}:/project aquasec/trivy fs /project > trivyfs.txt

    - name: Build Docker Image
      run: docker build --build-arg TMDB_V3_API_KEY=${{ env.TMDB_API_KEY }} -t netflix .

    - name: Log in to DockerHub
      run: echo "${{ env.DOCKER_PASSWORD }}" | docker login -u "${{ env.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker tag netflix ${{ env.DOCKER_USERNAME }}/netflix:latest
        docker push ${{ env.DOCKER_USERNAME }}/netflix:latest

    - name: Trivy Image Scan
      run: |
        docker run --rm aquasec/trivy image ${{ env.DOCKER_USERNAME }}/netflix:latest > trivyimage.txt

    - name: Deploy to Kubernetes
      uses: appleboy/scp-action@v0.1.0  # Corrected version
      with:
        host: ${{ secrets.K8S_MASTER_IP }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.K8S_PRIVATE_KEY }}
        source: "./k8s/*"
        target: "/tmp"

    - name: Apply Kubernetes Manifests
      uses: appleboy/ssh-action@v0.1.0  # Corrected version
      with:
        host: ${{ secrets.K8S_MASTER_IP }}
        username: ${{ secrets.K8S_USER }}
        key: ${{ secrets.K8S_PRIVATE_KEY }}
        script: |
          kubectl apply -f /tmp/deployment.yml
          kubectl apply -f /tmp/service.yml
          kubectl apply -f /tmp/ingress.yml  # If applicable, you can add ingress

